### ISSUE TITLE
Version 2.4: missing intel architecture?

### ISSUE THREAD

**Issue by suschizu** [mulot/SubnetCalc#10]
Hello - just recognised that the latest release just contains an ARM architecture - x86 is missing 

<img width="224" alt="Screenshot 2021-11-08 at 19 37 56" src="https://user-images.githubusercontent.com/16004333/140798752-9a56c124-dfa5-4c7d-9d86-c3b36c8461b5.png">

**Comment by mulot** [comment]
Hello. Where did you get the binary? On GitHub? On the Website or on the Mac App Store?

**Comment by suschizu** [comment]
I used the URL from the website:
http://subnetcalc.free.fr/download/subnetcalc-2.4.dmg 
but just looked into the GitHub download - it's also missing the intel architecture

**Comment by mulot** [comment]
Ok I've just upload a Universal binary on GitHub and the website.

**Comment by suschizu** [comment]
perfect thanks!
