### ISSUE TITLE
Support for /31 subnets

### ISSUE THREAD

**Issue by tmonsores** [mulot/SubnetCalc#4]
Could you please implement support for /31 prefixes? That's a perfectly valid IP prefix since RFC3021 (2020) and widely supported by all major vendors.

<img width="526" alt="Screen Shot 2021-02-11 at 09 41 33" src="https://user-images.githubusercontent.com/13514961/107637763-6bb15f00-6c4d-11eb-9b14-b18007fd5c11.png">

**Comment by mulot** [comment]
Hi Tiago,

It is supported in the version in development and should be supported in the next release.

King regards,
Julien

**Comment by tmonsores** [comment]
Hey Julien,

Thanks for the prompt reply! I will be waiting for the update then. I use /31 for all point-to-point connections on my network to save IP addresses, but I never know what will be the address on the other side, if it is +1 or -1. So it will be a nice addition to your app.

Keep up the good work!

My best regards,
Tiago
